package Texture;
import Texture.sounds.sound;
import Texture.AnimGLEventListener1.pair;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.*;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame implements KeyListener {

    public static Clip clip;

    public menu() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        File soundFile = Texture.sounds.sound.getSoundFile("game1.wav");
        AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);
        DataLine.Info info = new DataLine.Info(Clip.class, audioIn.getFormat());
        clip = (Clip) AudioSystem.getLine(info);
        clip.open(audioIn);
        clip.start();
        clip.loop(Clip.LOOP_CONTINUOUSLY);
        setSize(650, 650);
        setResizable(false);
        this.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        high = new javax.swing.JButton();
        instruction = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 650));
        setMinimumSize(new java.awt.Dimension(650, 650));
        setPreferredSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setBackground(new java.awt.Color(0, 0, 255));
        play.setForeground(java.awt.Color.ORANGE);
        play.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        play.setText("play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 160, 60));

        exit.setBackground(new java.awt.Color(0, 0, 255));
        exit.setForeground(java.awt.Color.ORANGE);
        exit.setFont(new java.awt.Font("Tekton Pro", 0, 38));
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 160, 60));

        sound.setBackground(new java.awt.Color(0, 0, 255));
        sound.setForeground(java.awt.Color.ORANGE);
        sound.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        sound.setText("sound");
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 160, 60));

        high.setBackground(new java.awt.Color(0, 0, 255));
        high.setForeground(java.awt.Color.ORANGE);
        high.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        high.setText("high score");
        high.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highActionPerformed(evt);
            }
        });
        getContentPane().add(high, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 160, 60));

        instruction.setBackground(new java.awt.Color(0, 0, 255));
        instruction.setForeground(java.awt.Color.ORANGE);
        instruction.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        instruction.setText("Instructions");
        instruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionActionPerformed(evt);
            }
        });
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texture/play.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    static String s;

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        s = JOptionPane.showInputDialog(null, "Enter your Name");

        Anim.reSet();
        this.dispose();
        clip.stop();
        // TODO add your handling code here:
    }
    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        new sound().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_soundActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void instructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionActionPerformed
        new how().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_instructionActionPerformed

    private void highActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highActionPerformed
        new Anim2().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_highActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu().setVisible(true);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton high;
    private javax.swing.JButton instruction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton play;
    private javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables


    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.setVisible(false);
            System.exit(0);
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}